# This is a basic workflow to help you get started with Actions


name: Test Coverage

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    ssteps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: 64f0459bc11f9673e92ad82e6807122dcb1b973766cfcbcd66973972e8ec7de5
    with:
      coverageCommand: npm run coverage
      debug: true
