name: Test Coverage
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v3.0.0
    env:
      CC_TEST_REPORTER_ID: 64f0459bc11f9673e92ad82e6807122dcb1b973766cfcbcd66973972e8ec7de5
    with:
      coverageCommand: npm run coverage
      debug: true
